import torch
from zviz import Zviz

conv0 = torch.nn.Conv2d(3, 3, 3)
conv1 = torch.nn.Conv2d(3, 3, 3)
# conv2 = resnet18()
# conv2=torch.nn.Sequential(torch.nn.Conv2d(3,3,3),torch.nn.Conv2d(3,3,3))
# model = torch.nn.Sequential(conv0, conv1)
zviz = Zviz({'conv0': conv0, 'conv1': conv1})
# optim = torch.optim.Adam(conv0.parameters())
optim = torch.optim.Adam(torch.nn.Sequential(conv0, conv1).parameters())
zviz.setoptimizer(optim, 'model')
# zviz.setoptimizer(optim2, '2')
data = torch.randn(3, 3, 256, 256)
data2 = torch.randn(3, 3, 256, 256)
out = conv0(data)
out2 = conv1(out)
loss = out.mean() + out2.mean()
# loss2 = out2.mean()
zviz.backward(loss)
# zviz.backward(loss2)
zviz.step('model')
# zviz.step('2')

# zviz.zero_grad('model')
# zviz.zero_grad('2')